package com.plog.domain.integration.entity;

/** provider 원문을 보존하는 최소 활동 분류다. 기여도 계산 규칙은 이 분류에 두지 않는다. */
public enum IntegrationActivityType {
    GITHUB_COMMIT,
    GITHUB_PULL_REQUEST,
    GITHUB_PULL_REQUEST_REVIEW,
    GITHUB_ISSUE,
    GITHUB_ISSUE_COMMENT,
    GITHUB_ISSUE_EVENT,
    NOTION_DATA_SOURCE_SNAPSHOT,
    NOTION_PAGE_SNAPSHOT,
    NOTION_BLOCK_SNAPSHOT,
    NOTION_COMMENT,
    NOTION_WEBHOOK_EVENT,
    GOOGLE_DRIVE_FILE_SNAPSHOT,
    GOOGLE_DRIVE_ACTIVITY,
    GOOGLE_DRIVE_COMMENT,
    GOOGLE_DRIVE_REVISION,
    GOOGLE_DOCUMENT_SUGGESTION,
    GOOGLE_PRESENTATION_SNAPSHOT,
    FIGMA_FILE_VERSION,
    FIGMA_FILE_METADATA,
    FIGMA_COMMENT,
    FIGMA_COMMENT_REACTION
}
