package com.plog.domain.report.entity;

/**
 * 도메인별 원본 활동 세부 유형. 외부 연동 값은 {@code IntegrationActivityType}과 이름을 맞췄지만
 * report 도메인이 integration 도메인에 의존하지 않도록 별도로 정의한다(상완이 변환 시 매핑).
 */
public enum RawActivityType {

    // TASK
    TASK_STATUS_CHANGE, TASK_ATTACHMENT_ADD,

    // CHAT
    CHAT_MESSAGE,

    // POST
    POST_CREATE, COMMENT_CREATE,

    // EVALUATION
    PEER_EVALUATION_SUBMIT, SELF_FEEDBACK_SUBMIT,

    // GITHUB
    GITHUB_COMMIT, GITHUB_PULL_REQUEST, GITHUB_PULL_REQUEST_REVIEW,
    GITHUB_ISSUE, GITHUB_ISSUE_COMMENT, GITHUB_ISSUE_EVENT,

    // FIGMA
    FIGMA_FILE_VERSION, FIGMA_COMMENT, FIGMA_FILE_METADATA, FIGMA_COMMENT_REACTION,

    // GOOGLE
    GOOGLE_DRIVE_ACTIVITY, GOOGLE_DRIVE_REVISION, GOOGLE_DOCUMENT_SUGGESTION,
    GOOGLE_DRIVE_COMMENT, GOOGLE_DRIVE_FILE_SNAPSHOT, GOOGLE_PRESENTATION_SNAPSHOT,

    // NOTION (점수 계산 제외, 근거 텍스트/신뢰도 등급 용도로만 사용)
    NOTION_DATA_SOURCE_SNAPSHOT, NOTION_PAGE_SNAPSHOT, NOTION_BLOCK_SNAPSHOT, NOTION_COMMENT
}