CREATE TABLE IF NOT EXISTS posts (
    post_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_member_id bigint NOT NULL,
    content text NOT NULL,
    is_notice boolean NOT NULL DEFAULT false,
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL
);
